### ISSUE TITLE
Provide examples for how to 

### ISSUE THREAD

**Issue by bbrewington** [fascinatingfingers/ZillowR#1]
In the Readme, it may help to provide a couple examples of how to "use functions from the XML package to extract the desired output" --> I'm working through this now, and will share some examples along if I figure it out

- **"response"** an XMLNode with the API-specific response values. At this time, no further coercion is performed, so you may have to use functions from the XML package to extract the desired output.

**Comment by svfrey** [comment]
Hey, any follow-up on this? I'm working on a project using ZillowR right now but after a bit of poking around, it's a little bit obfuscated re: exactly how I'm supposed to get data out of the XMLNode. Were you able to gather anything from your adventures with this package? If not, I might just end up switching over to pyzillow and seeing if that grabs data in a more easily viewable format.
